name: post
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# environment:
#   sdk: ">=2.0.0-dev.68.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  email_validator: ^2.1.17
  url_launcher: ^6.1.6
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  fluttericon: ^2.0.0
  http: ^0.13.5
  html: ^0.15.1
  blur: ^3.0.0
  flutter_image_slideshow: any
  dots_indicator: ^2.1.0
  conditional_builder: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.6
  responsive_sizer: ^3.1.1
  intl: ^0.17.0
  provider: ^6.0.3
  animated_tree_view: ^1.0.0
  buttons_tabbar: ^1.3.6
  flutter_staggered_grid_view: ^0.6.2
  mockito: ^5.3.2
  build_runner: ^2.3.2
  dartdoc: ^6.1.2
  flutter_switch: ^0.3.2
  badges: ^2.0.3
  linter: ^1.30.0
  get: ^4.6.5
  dotted_border: any
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.6
  multi_image_picker: ^4.7.14
  shared_preferences: ^2.0.15
  hexcolor: ^2.0.1
  video_player: ^2.4.8
  flutter_quill: ^6.1.6
  custom_refresh_indicator: ^2.0.1
  fluttertoast: ^8.1.2
  #html_editor_enhanced: ^2.5.0
  # flutter_signin_button: ^2.0.0
  flutter_local_notifications: any
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  cached_network_image: ^3.2.3
  dropdown_search: ^5.0.5
  visibility_detector: ^0.3.3
  chewie: ^1.3.6
  inview_notifier_list: ^3.0.0
  link_preview_generator:
    git:
      url: https://github.com/Amr146/link_preview_generator.git
  expandable_page_view: ^1.0.17
  flutter_html: ^2.1.1
  responsive_framework: ^0.2.0
  device_preview: ^1.1.0
  flutter_recaptcha_v3: ^0.1.2
  draw_graph: ^1.0.0
  editable: ^2.0.0

dev_dependencies:
  test_cov_console: ^0.2.2

  # test_coverage: any
  flutter_test:
    sdk: flutter
  flutter_code_style: ^2.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Plus
      fonts:
        - asset: assets/icons/Plus.ttf
    - family: Penciel
      fonts:
        - asset: assets/icons/Penciel.ttf
    - family: closeIcons
      fonts:
        - asset: assets/icons/close_icons.ttf
    - family: RedditIcons
      fonts:
        - asset: assets/icons/reddit_icons.ttf
    - family: GoogleFacebookIcons
      fonts:
        - asset: assets/icons/google_facebook_icons.ttf
    - family: SettingsIcons
      fonts:
        - asset: assets/icons/settings_icons.ttf
    - family: ArrowHeadDownWord
      fonts:
        - asset: assets/icons/arrow_head_down_ward.ttf
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana.ttf
        - asset: assets/fonts/verdanab.ttf
          weight: 700
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/reddit_community_search.png
    - assets/images/reddit-logins.png
    - assets/images/community_icon.png
    - assets/images/envelope.png
    - assets/images/Activism.png
    - assets/images/Addiction Support.png
    - assets/images/Animal and Pets.png
    - assets/images/Anime.png
    - assets/images/upvote.png
    - assets/images/img.jpg
    - assets/images/emptyNotification.png
    - assets/images/redditLoading.png
    - assets/images/loadingreddit.gif
    - assets/images/arrow-up.png
    - assets/images/user.png
    - assets/images/heart.png
    - assets/images/notification.png
    - assets/images/rise.png
    - assets/images/megaphone.png
    - assets/images/pink-ribbon.png
    - assets/images/cat.png
    - assets/images/brush.png
    - assets/images/nail-polish.png
    - assets/images/stats.png
    - assets/images/gear.png
    - assets/images/steering-wheel.png
    - assets/images/sun-glasses.png
    - assets/images/paint-roller.png
    - assets/images/baby.png
    - assets/images/clothes-hanger.png
    - assets/images/shoe.png
    - assets/images/fork.png
    - assets/images/happy-face.png
    - assets/images/joystick.png
    - assets/images/gender.png
    - assets/images/waiting.png
    - assets/images/car.png
    - assets/images/plant.png
    - assets/images/cursor.png
    - assets/images/balance.png
    - assets/images/machine-learning.png
    - assets/images/shopping-bag.png
    - assets/images/-18.png
    - assets/images/molecule.png
    - assets/images/link.png
    - assets/images/corporate.png
    - assets/images/first-aid-bag.png
    - assets/images/masculine.png
    - assets/images/alien-ship.png
    - assets/images/rank.png
    - assets/images/clapperboard.png
    - assets/images/headphones.png
    - assets/images/tree.png
    - assets/images/pin.png
    - assets/images/podcasts.png
    - assets/images/court.png
    - assets/images/keyboard.png
    - assets/images/book.png
    - assets/images/koran.png
    - assets/images/flask.png
    - assets/images/rainbow.png
    - assets/images/ball.png
    - assets/images/strategy.png
    - assets/images/cpu.png
    - assets/images/tv.png
    - assets/images/love.png
    - assets/images/airplane.png
    - assets/images/femenine.png
    - assets/images/newspaper.png
    - assets/images/atom.png
    - assets/images/otaku.png
    - assets/images/up-arrow.png
    - assets/images/default-img.png
    - assets/images/reddit.png
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



